# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Instastructure' do
    pod 'Parse'
    pod 'AFNetworking'
    pod 'IQDropDownTextField'
end

target 'InstastructureTests' do

end

target 'InstastructureUITests' do

end

